version: "3.4"
services:

  adventure-works.db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: "Password.123"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"

  mongo:
    image: mongo:4.0.4
    ports:
    - "27017:27017"